theme: jekyll-theme-minimal
title: Toto's Personal Website
description: Bookmark this to follow my personal blog, project updates, and more!

# Customize the appearance
accent_color: "#3498db"
background_color: "#f4f4f9"
text_color: "#333"

# Site details
author: "Toto"
email: "toto@example.com"
